name: test github actions
on: push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Using
        run: make setup
      - name: Run tests
        run: make setup
      - name: Run linter
        run: make lint

